SoftNetCore.Web/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using SoftNetCore.Services.Loggings;
using SoftNetCore.Services.Interface;
using System.Threading.Tasks;
using Microsoft.Extensions.Options;
using System.Net.Http;
using SoftNetCore.Model.Catalog;
using Newtonsoft.Json;
using SoftNetCore.Common.Helpers;
using X.PagedList;
using System.Linq;

namespace SoftNetCore.Web.Controllers
{
    public class ArticleController : Controller
    {
        #region Fields
        private readonly IAboutService _aboutService;
        private readonly IArticleService _articleService;
        private readonly IArticleCategoryService _articleCategoryService;
        private readonly ILogging _logging;
        #endregion
        #region Ctor
        public ArticleController(IArticleService articleService, IArticleCategoryService articleCategoryService, IAboutService aboutService, ILogging logging)
        {
            _aboutService = aboutService;
            _articleService = articleService;
            _articleCategoryService = articleCategoryService;
            _logging = logging;
        }
        #endregion

        [HttpGet]
        [Route("tin-tuc")]
        [Route("tin-tuc-{title}-{id}")]
        [Route("tin-tuc-{id}")]
        public async Task<IActionResult> Index(int? id, int? page)
        {
            string titleCat = string.Empty;
            int pageNumper = 0;
            int.TryParse(page.ToString(), out pageNumper);
            if (pageNumper == 0)
                pageNumper = 1;

            if (id != null)
            {
                var item = await _articleCategoryService.FindById(id.ToInt());
                titleCat = $"<span></span><a href=\"/tin-tuc\">Tin Tức</a>";
                titleCat += $"<span></span>{item.Title}";
            }
            else
            {
                titleCat = "<span></span>Tin Tức";
            }
            ViewBag.TitleCat = titleCat;
            ViewBag.CatId = id ?? 0;
            //ViewBag.Catgory = await _articleCategoryService.GetByStatusAsync(true);
            ViewBag.Info = await _aboutService.GetFisrtAsync(1);
            
            IPagedList<ArticleModel> data = id == null ? (await _articleService.GetByStatusAsync(true)).ToPagedList(pageNumper, 15) : (await _articleService.GetByCategoryAsync(id.ToInt())).ToPagedList(pageNumper, 15);
           
            return View(data);
        }

        [HttpGet]
        [Route("chi-tiet-tin-tuc")]
        [Route("chi-tiet-tin-tuc-{title}-{id}")]
        public async Task<IActionResult> Detail(int id)
        {
            var result = await _articleService.FindById(id);
            var item = await _articleCategoryService.FindById(result.ArticleCategoryId.ToInt());
            ViewBag.TitleCat = item?.Title;
            ViewBag.Info = await _aboutService.GetFisrtAsync(1);

            return View(result);
        }
    }
}

SoftNetCore.Web/Views/Shared/Components/HomeArticle/Default.cshtml
@using SoftNetCore.Model.Catalog;
@using SoftNetCore.Common.Helpers;
@model IList<ArticleModel>

<div class="blog-area pt-30 pb-70">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="heading-title heading-style pos-rltv mb-50 text-center">
                    <h3 class="uppercase">Tin tức & Sự kiện</h3>
                </div>
                <div class="total-blog">
                    @foreach (var item in Model)
                    {
                        <div class="blog-item">
                            <div class="single-blog">
                                <div class="blog-img pos-rltv product-overlay">
                                    <a asp-controller="Article" asp-action="Detail" asp-route-id="@item.Id" asp-route-title="@item.Title.ToUrlFormat()">
                                        <img src="/@item.Thumb" alt="@item.Title">
                                    </a>
                                </div>
                                <div class="blog-content">
                                    <div class="blog-title">
                                        <h5>
                                            <a asp-controller="Article" asp-action="Detail" asp-route-id="@item.Id" asp-route-title="@item.Title.ToUrlFormat()">@item.Title</a>
                                        </h5>
                                        <div class="like-comments-date">
                                            <ul>
                                                <li>
                                                    <a href="#">
                                                        <i class="zmdi zmdi-comment-outline"></i>@item.ViewTime.ToInt()
                                                        Lượt xem
                                                    </a>
                                                </li>
                                                <li class="blog-date">
                                                    <a href="#">
                                                        <i class="zmdi zmdi-calendar-alt"></i>@item.CreateTime.ToStringDateTime("dd/MM/yyyy")
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="blog-text">
                                            <p>
                                                @item.Description.SubStringWithLength(165, false, true)
                                            </p>
                                        </div>
                                        <a class="read-more montserrat" asp-controller="Article" asp-action="Detail" asp-route-id="@item.Id" asp-route-title="@item.Title.ToUrlFormat()">Xem thêm</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>